// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDDzUU-RpJEp_Jub2aXEv8L82_i3gBls',
    appId: '1:316884545777:web:84d506f77ad6a012c67950',
    messagingSenderId: '316884545777',
    projectId: 'smartroll-35e41',
    authDomain: 'smartroll-35e41.firebaseapp.com',
    storageBucket: 'smartroll-35e41.firebasestorage.app',
    measurementId: 'G-W104Z05M5X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqw_xQbIwkTSSssHykIT0nqq5dfyfMZU',
    appId: '1:316884545777:ios:0e518e9b9869f7e2c67950',
    messagingSenderId: '316884545777',
    projectId: 'smartroll-35e41',
    storageBucket: 'smartroll-35e41.firebasestorage.app',
    iosBundleId: 'com.uos.smartroll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqw_xQbIwkTSSssHykIT0nqq5dfyfMZU',
    appId: '1:316884545777:ios:fb595faac82822f3c67950',
    messagingSenderId: '316884545777',
    projectId: 'smartroll-35e41',
    storageBucket: 'smartroll-35e41.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeE_5ofCgWP0f9CtL01fAvGdKS-O0r3Rg',
    appId: '1:316884545777:android:495b156f759b0952c67950',
    messagingSenderId: '316884545777',
    projectId: 'smartroll-35e41',
    storageBucket: 'smartroll-35e41.firebasestorage.app',
  );

}